# # Use a smaller base image for production
# FROM node:21-bullseye

# # Set the working directory
# WORKDIR /app/frontend

# # Copy only necessary files for installing dependencies
# COPY package.json .
# COPY package-lock.json .

# # Install dependencies
# RUN npm install --production

# # Copy the application code
# COPY . .


# # Start the application
# CMD ["npm", "build"]
