# Use a smaller base image for production
FROM node:lts-alpine

# Set the working directory
WORKDIR /app

# Copy only necessary files for installing dependencies
COPY ./package.json .
COPY ./package-lock.json .

# Install dependencies
RUN npm install -g npm && npm install

# Copy the application code
COPY . .


# Start the application
# RUN npm run build

CMD ["npm", "run", "build"]

