version: '3'

volumes:
  intellicram-data:
    external: true

services:
  backend-fastapi:
    environment:
      DATABASE_URL: ${DATABASE_URL}
      WAIT_HOSTS: ${WAIT_HOSTS}
      PORT: ${PORT}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SECRET_KEY:  ${SECRET_KEY}
      ALGORITHM:  ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES:  ${ACCESS_TOKEN_EXPIRE_MINUTES}
      VITE_API_URL: ${VITE_API_URL}
      FASTAPI_API_URL: ${FASTAPI_API_URL}
    build:
      context: backend
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "15432:5432"
    volumes:
      - intellicram-data:/var/lib/postgresql/data

  frontend-vite:
    build:
      context: ../IntelliCram-FE/frontend/ # make this relative to where you have your frontend folder
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../IntelliCram-FE/frontend/:/app # make this relative to where you have your frontend folder
    environment:
      VITE_API_URL: ${VITE_API_URL}