FROM python:3.10-slim

RUN adduser --disabled-password myuser
USER myuser

WORKDIR /app

COPY requirements.txt requirements.txt
COPY main.py main.py

COPY migrations migrations
COPY models models
COPY repos repos
COPY routers routers

RUN python -m pip install --upgrade pip \
    && python -m pip install -r requirements.txt

CMD python -m migrations up && uvicorn main:app --host 0.0.0.0 --port 8000
